package main

import (
	"context"
	"database/sql"
	"fmt"
	"net/http"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/golang-migrate/migrate/v4"
	"github.com/golang-migrate/migrate/v4/database/postgres"
	_ "github.com/golang-migrate/migrate/v4/source/file"
	_ "github.com/lib/pq"
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	"snailbus/internal/handlers"
	"snailbus/internal/logger"
	"snailbus/internal/metrics"
	"snailbus/internal/middleware"
	"snailbus/internal/storage"

	_ "snailbus/docs" // swagger docs generated by swag
)

var (
	registerMetricsOnce sync.Once
)

// Version information set at build time via ldflags
var (
	Version   = "dev"
	Commit    = "unknown"
	BuildTime = "unknown"
)

// @title           Snailbus API
// @version         1.0.0
// @description     Snailbus is a data ingestion and management API for receiving and storing system information collected by snail-core agents.
// @description     The API provides endpoints for ingesting collection reports from snail-core agents, querying and managing host data, and health monitoring.
// @description     All timestamps are in RFC3339 format (ISO 8601).

// @contact.name   Snailbus API Support
// @contact.url    https://github.com/sluggisty/snailbus

// @license.name  MIT
// @license.url   https://opensource.org/licenses/MIT

// @host      localhost:8080
// @BasePath  /

// @schemes   http https

func main() {
	// Initialize structured logging
	logger.Init()

	// Initialize database connection
	databaseURL := getEnv("DATABASE_URL", "postgres://snail:snail_secret@localhost:5432/snailbus?sslmode=disable")

	// Run migrations first
	if err := runMigrations(databaseURL); err != nil {
		logger.Logger.Fatal().Err(err).Msg("Failed to run migrations")
	}

	// Initialize storage
	store, err := storage.NewPostgresStorage(databaseURL)
	if err != nil {
		logger.Logger.Fatal().Err(err).Msg("Failed to initialize storage")
	}
	defer store.Close()

	// Register database metrics
	metrics.RegisterDBMetrics(store.DB(), "snailbus")

	// Register Go runtime metrics (only once, ignore if already registered)
	registerMetricsOnce.Do(func() {
		// Try to register Go collector
		if err := prometheus.Register(prometheus.NewGoCollector()); err != nil {
			// Check if it's an AlreadyRegisteredError - this is expected and harmless
			if _, ok := err.(prometheus.AlreadyRegisteredError); ok {
				// Already registered, this is fine - don't log as it's expected
			} else {
				// Some other error - log it
				logger.Logger.Warn().Err(err).Msg("Failed to register Go collector")
			}
		}
		// Try to register Process collector
		if err := prometheus.Register(prometheus.NewProcessCollector(prometheus.ProcessCollectorOpts{})); err != nil {
			// Check if it's an AlreadyRegisteredError - this is expected and harmless
			if _, ok := err.(prometheus.AlreadyRegisteredError); ok {
				// Already registered, this is fine - don't log as it's expected
			} else {
				// Some other error - log it
				logger.Logger.Warn().Err(err).Msg("Failed to register Process collector")
			}
		}
	})

	// Create handlers
	h := handlers.New(store)

	// Create Gin router
	r := gin.Default()

	// Add request ID middleware (should be first to capture all requests)
	r.Use(middleware.RequestIDMiddleware())

	// Add metrics middleware (should be early to capture all requests)
	r.Use(middleware.MetricsMiddleware())

	// Health check endpoint
	r.GET("/health", h.Health)

	// Root endpoint
	r.GET("/", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message":    "Welcome to Snailbus API",
			"version":    Version,
			"commit":     Commit,
			"build_time": BuildTime,
		})
	})

	// API v1 routes
	v1 := r.Group("/api/v1")
	{
		// Public auth endpoints (no authentication required)
		auth := v1.Group("/auth")
		{
			auth.POST("/register", h.Register)
			auth.POST("/login", h.Login)
			auth.POST("/api-key", h.GetAPIKeyFromCredentials) // Get API key from username/password
		}

		// Protected routes (require API key authentication)
		protected := v1.Group("")
		protected.Use(middleware.AuthMiddleware(store))
		protected.Use(middleware.OrgContextMiddleware()) // Extract org_id and role for easy access
		{
			// Auth endpoints - accessible to all authenticated users
			protected.GET("/auth/me", h.GetMe)

			// API key management - accessible to all authenticated users
			protected.POST("/api-keys", h.CreateAPIKey)
			protected.GET("/api-keys", h.ListAPIKeys)
			protected.DELETE("/api-keys/:id", h.DeleteAPIKey)

			// Host management endpoints - viewing accessible to all authenticated users
			protected.GET("/hosts", h.ListHosts)
			protected.GET("/hosts/:host_id", h.GetHost)

			// Host deletion - requires editor or admin role
			editorOrAdmin := protected.Group("")
			editorOrAdmin.Use(middleware.RequireRole("editor", "admin"))
			{
				editorOrAdmin.DELETE("/hosts/:host_id", h.DeleteHost)
			}

			// User management endpoints - admin only
			adminOnly := protected.Group("")
			adminOnly.Use(middleware.RequireRole("admin"))
			{
				adminOnly.GET("/users", h.ListUsers)
				adminOnly.POST("/users", h.CreateUser)
				adminOnly.PUT("/users/:user_id/role", h.UpdateUserRole)
				adminOnly.DELETE("/users/:user_id", h.DeleteUser)
			}
		}

		// Ingest endpoint - requires editor or admin role (viewers cannot upload)
		ingest := v1.Group("")
		ingest.Use(middleware.AuthMiddleware(store))
		ingest.Use(middleware.OrgContextMiddleware()) // Extract org_id and role
		ingest.Use(middleware.RequireRole("editor", "admin"))
		{
			ingest.POST("/ingest", h.Ingest)
		}
	}

	// OpenAPI specification endpoints (generated by swag)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Legacy endpoints for backward compatibility (now serve generated spec)
	r.GET("/openapi.yaml", h.GetOpenAPISpecYAML)
	r.GET("/openapi.json", h.GetOpenAPISpecJSON)

	// Start main API server
	port := getEnv("PORT", "8080")
	apiServer := &http.Server{
		Addr:    ":" + port,
		Handler: r,
	}

	// Start metrics server on separate port (default: localhost:9090)
	// This provides network-level security - metrics are only accessible from localhost/internal network
	metricsPort := getEnv("METRICS_PORT", "9090")
	metricsBindAddr := getEnv("METRICS_BIND_ADDRESS", "127.0.0.1")
	metricsMux := http.NewServeMux()
	metricsMux.Handle("/metrics", promhttp.Handler())
	metricsServer := &http.Server{
		Addr:    metricsBindAddr + ":" + metricsPort,
		Handler: metricsMux,
	}

	// Start both servers concurrently
	var wg sync.WaitGroup
	wg.Add(2)

	// Start main API server
	go func() {
		defer wg.Done()
		logger.Logger.Info().
			Str("port", port).
			Str("version", Version).
			Str("commit", Commit).
			Str("build_time", BuildTime).
			Msg("Starting Snailbus API server")
		if err := apiServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Logger.Fatal().Err(err).Msg("Failed to start API server")
		}
	}()

	// Start metrics server
	go func() {
		defer wg.Done()
		logger.Logger.Info().
			Str("address", metricsBindAddr).
			Str("port", metricsPort).
			Msg("Starting metrics server")
		if err := metricsServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			logger.Logger.Fatal().Err(err).Msg("Failed to start metrics server")
		}
	}()

	// Wait for interrupt signal to gracefully shutdown the servers
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit

	logger.Logger.Info().Msg("Shutting down servers...")

	// Gracefully shutdown API server
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	if err := apiServer.Shutdown(ctx); err != nil {
		logger.Logger.Error().Err(err).Msg("Error shutting down API server")
	}

	// Gracefully shutdown metrics server
	if err := metricsServer.Shutdown(ctx); err != nil {
		logger.Logger.Error().Err(err).Msg("Error shutting down metrics server")
	}

	logger.Logger.Info().Msg("Servers stopped")
}

// runMigrations runs database migrations
func runMigrations(databaseURL string) error {
	// Parse database URL to get driver instance
	db, err := sql.Open("postgres", databaseURL)
	if err != nil {
		return fmt.Errorf("failed to open database for migrations: %w", err)
	}
	defer db.Close()

	driver, err := postgres.WithInstance(db, &postgres.Config{})
	if err != nil {
		return fmt.Errorf("failed to create migration driver: %w", err)
	}

	// Get migrations directory from environment or use default
	migrationsPath := getEnv("MIGRATIONS_PATH", "file://migrations")

	m, err := migrate.NewWithDatabaseInstance(
		migrationsPath,
		"postgres",
		driver,
	)
	if err != nil {
		return fmt.Errorf("failed to create migrate instance: %w", err)
	}

	// Run migrations
	if err := m.Up(); err != nil && err != migrate.ErrNoChange {
		return fmt.Errorf("failed to run migrations: %w", err)
	}

	if err == migrate.ErrNoChange {
		logger.Logger.Info().Msg("Database is up to date, no migrations to run")
	} else {
		logger.Logger.Info().Msg("Database migrations completed successfully")
	}

	return nil
}

// getEnv gets an environment variable or returns a default value
func getEnv(key, defaultValue string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return defaultValue
}
